### ISSUE TITLE
vok-helloworld-app: navigateToView missing

### ISSUE THREAD

**Issue by a-cosmic-jaw** [mvysny/vaadin-on-kotlin#102]
<img width="816" alt="Screenshot 2024-04-18 at 13 00 47" src="https://github.com/mvysny/vaadin-on-kotlin/assets/73474441/36263067-6c3a-4f55-8f58-37bbb59b8f3f">

Relevant code [here](https://github.com/a-cosmic-jaw/vok-helloworld-app/commit/d6c207931374f219420f280f859fb8c8e59ad90d)!

**Comment by mvysny** [comment]
Uh-oh, VoK changed quite a bit, I need to bring the project up-to-date. Thank you for letting me know!

I think the function is now called `navigateTo()` and should come from `karibu-tools-0.20.jar`.

**Comment by a-cosmic-jaw** [comment]
Ok, I'll take a look!
I lucked out and found `fun navigateTo(articleId: Long) = UI.getCurrent().navigate(ArticleView::class.java, articleId)` in your bookstore-vok example :)

**Comment by mvysny** [comment]
Excellent find! Unfortunately bookstore-vok is also a bit older, I'll upgrade that one as well, tomorrow latest. This project is up-to-date, please use it as a reference: https://github.com/mvysny/beverage-buddy-vok

**Comment by mvysny** [comment]
Alrighty, vok-helloworld-app and bookstore-vok are now upgraded to newest vok, please take a look :) The documentation is hopelessly outdated though, I need to fix that one as well.

**Comment by mvysny** [comment]
Alrighty, everything should be updated, including the documentation. Closing as fixed, please feel free to open new tickets as necessary.
