### ISSUE TITLE
Duplicates the records when it is edited

### ISSUE THREAD

**Issue by NiranjanShah** [mvysny/vaadin-on-kotlin#11]
In the Save of EditArticleView

val article = Article() must be val article = Article(articleId).

else is it creating a new record

**Comment by mvysny** [comment]
You're right, thank you for letting me know. The code is correct in the https://github.com/mvysny/vok-helloword-app repo (the `complete` branch); however it is broken in the VoK tutorial at http://www.vaadinonkotlin.eu/gettingstarted.html

**Comment by mvysny** [comment]
The issue should now be fixed; please feel free to reopen if anything comes up.
