### ISSUE TITLE
Assistance Required

### ISSUE THREAD

**Issue by NiranjanShah** [mvysny/vaadin-on-kotlin#16]
Can you please help us in using the thru gradle

1. grid-renderers-collection-addon-2.2.10

**Comment by mvysny** [comment]
The home page for this extension is https://vaadin.com/directory/component/grid-renderers-collection-for-vaadin7

It can be added to your maven project by adding
```xml
<dependency>
   <groupId>com.vaadin</groupId>
   <artifactId>grid-renderers-collection-addon</artifactId>
   <version>2.2.10</version>
</dependency>

<repository>
   <id>vaadin-addons</id>
   <url>http://maven.vaadin.com/vaadin-addons</url>
</repository>
```

That translated to Gradle as follows:
```groovy
repositories {
  maven { url "http://maven.vaadin.com/vaadin-addons" }
}
dependencies {
  compile "com.vaadin:grid-renderers-collection-addon:2.2.10"
}
```

It seems that this addon also provides client-side code and hence you need to recompile the client-side widgetset. This should be automatically handled by the Vaadin Gradle Plugin - it should detect that one of the dependencies contains client-side code, it should create a proper widgetset, compile it and then include it into the WAR file.

Everything should be explained at [Adding Addons to Vaadin Gradle Plugin](https://github.com/johndevs/gradle-vaadin-plugin/wiki/Using-addons).

**Comment by mvysny** [comment]
To verify that the widgetset has been compiled, the `src/main/webapp/VAADIN/widgetsets` directory must be non-empty and populated with the javascript code.

**Comment by mvysny** [comment]
Closing as answered.
