### ISSUE TITLE
How to Define the grid label

### ISSUE THREAD

**Issue by jiangzhixiao** [mvysny/vaadin-on-kotlin#22]
@mvysny ,hi, how to add custom grid column label?
in your example ,i can define a column by  addColumnFor(Person::name),and this column label is Name.
if i want to redefine the label to "Person Name",how to do this,thank you very much !

**Comment by mvysny** [comment]
Hi, thanks for the question! The `addColumnFor()` function allows you to configure the column in a block. So with Vaadin 8 you can write:
```kotlin
            addColumnFor(Person::name) {
                caption = "Person Name"
            }
```
For Vaadin 10 it is slightly different:
```kotlin
            addColumnFor(Person::name) {
                setHeader("Person Name")
            }
```
I have to write up a documentation for the `Grid` component.
```

**Comment by mvysny** [comment]
Closing as answered, please reopen if it doesn't work for you.

**Comment by jiangzhixiao** [comment]
thanks，i will try it tomorrow
