### ISSUE TITLE
Question / Enhancement

### ISSUE THREAD

**Issue by DALDEI** [mvysny/vaadin-on-kotlin#27]
Could you suggest a path to take to implement 'expanding' menu on left nav ?
I don't have tight requirements, the use case is that I'm getting to many top level menu entries so would like to implement the 'sections' as a kind of accordion or 'expando' or something similar.
I dont want to write it from scratch as I suspect theres 'hidden magic' attempting to get the styles right.

Breadcrumbs as a stretch request :)

**Comment by mvysny** [comment]
Hi David, thanks for letting me know! Sorry I'm on a vacation right now so I can't look at this right now.

From the top of my head, I'm not aware of any built-in CSS magic regarding this expanding stuff... But I have a couple of ideas. First idea is to add all menu buttons (using the `ValoMenu.menuButton()` function) and add a CSS class with some left padding rule to some of the buttons, to simulate the tree; you can then toggle the visibility of the buttons to simulate the expand/collapse.
Or, even better, you can perhaps add a Vaadin `Tree` component into the `ValoMenu` - with proper styling the Tree can imitate a tree-like expanding/collapsing menu.

**Comment by DALDEI** [comment]
Closing this -- I havent tested your additions but they look good, and the  need is no longer imperitive. thanks.
