### ISSUE TITLE
Button examples incorrect

### ISSUE THREAD

**Issue by DALDEI** [mvysny/vaadin-on-kotlin#34]
Several places in the docs are samples like:

```
        button("Back", { navigateToView<ArticlesView>() }) {
            styleName = ValoTheme.BUTTON_LINK
        }
```

that doesnt work for me -- perhaps nativeButton -- but for button I need to do:

```
        button("Back"){
             onLeftCLick { navigateToView<ArticlesView>() } 
            styleName = ValoTheme.BUTTON_LINK
        }

```

**Comment by mvysny** [comment]
Hmm I've reviewed http://www.vaadinonkotlin.eu/gettingstarted.html and couldn't a bug you speak of. Could you please list exact places, or fix that with a PR?

**Comment by DALDEI** [comment]
I was hallucinating or its been fixed.  Thanks.
