### ISSUE TITLE
support vaadin-flow gradle pligin product mode

### ISSUE THREAD

**Issue by icode** [mvysny/vaadin-on-kotlin#35]
id com.devsoap.vaadin-flow

Can not use this plugin now, some resource not found (404)
Maybe kotlin dsl annotations not process

**Comment by stapel** [comment]
We had some problems with this as well, it seemed that `AssembleClientDependencies` was never executed, my workaround is:

```groovy
if (vaadin.productionMode) {
    war.dependsOn(AssembleClientDependenciesTask.NAME)
}
```

**Comment by mvysny** [comment]
Thank you, sounds like a bug. Let me test this please, with the newest Vaadin Flow Gradle plugin and with the suggested workaround.

**Comment by mvysny** [comment]
Gradle Flow plugin unfortunately currently doesn't support npm mode at all (only a paid Beta does). However there is another plugin planned, hopefully February 2020.

That being said, it should support production mode with Vaadin 14 compatibility mode. Could you confirm that you're using compat mode?

**Comment by mvysny** [comment]
The new [Vaadin Gradle Plugin](https://github.com/vaadin/vaadin-gradle-plugin) is now available and integrated into VoK. VoK now by default uses Vaadin 14 npm mode. For a proper workflow on how to build your app in production mode please see the Vaadin Gradle Plugin page.
