### ISSUE TITLE
v-bump to vok-orm 1.0

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-on-kotlin#40]
vok-orm is now based on JDBI and jdbi-orm. Steps needed:

[x] Release VoK 0.8 with the new vok-orm
[x] Update all VoK guides

**Comment by mvysny** [comment]
VoK now uses JDBI under the hood. Hopefully all of the guides have now been converted to the new vok-orm; if not, just let me know :)

**Comment by stapel** [comment]
Works great, had to derive a Dao to override getRowMapper to return a KotlinMapper though. :)

**Comment by mvysny** [comment]
@stapel oh, I haven't realized the need for such a mapper. Could you please open a bug report (probably at https://github.com/mvysny/vok-orm/issues ) and write in a bit more detail which additional use-cases are handled by KotlinMapper?
