### ISSUE TITLE
trimmingConverter for FilterBar?

### ISSUE THREAD

**Issue by jhult** [mvysny/vaadin-on-kotlin#45]
[Karibu-DSL](/mvysny/karibu-dsl) has a [trimmingConverter](/mvysny/karibu-dsl/blob/master/karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/BinderUtils.kt#L24) available. It would be nice if this (or something similar) was available for a [FilterBar](/mvysny/vaadin-on-kotlin/blob/master/vok-util-vaadin10/src/main/kotlin/eu/vaadinonkotlin/vaadin10/FilterBar.kt).

**Comment by mvysny** [comment]
Awesome feedback, thank you so much! Could you please create separate issues for every topic, so that it can be discussed separately? We can then focus on discussing the String trimming in filters.

**Comment by mvysny** [comment]
Regarding the PredicateFilterFactory: https://github.com/mvysny/vaadin-on-kotlin/issues/46

**Comment by mvysny** [comment]
> I converted from the original Grid filtering available to the new FilterBar method in the past few weeks. That was quite the effort as it took me a while to figure everything out. However, I did eventually get it all converted over.

I'm sorry to hear that, but I'm happy that you managed to do the conversion. I think the new API is better since it puts you in control (as opposed to the old auto-generator API where you had to hook into certain places to get the behaviour you needed). However, I need to keep the backward compatibility in mind also, to ease the migration path.

**Comment by mvysny** [comment]
> I couldn't use LocalDate.toFilter() because it was private.

Could you please open a new feature request and write your use-case for using a single DatePicker as a filter component? Perhaps we can include your excellent code into VoK if the use-case is generic enough.

**Comment by mvysny** [comment]
If I'm not mistaken, this leaves only the original issue to be implemented. Even though `ILikeFilter`, `LikeFilter` and `FullTextFilter` perform automatic trimming, `eq()` does not, so `trimmingConverter()` still makes sense. I'll implement :+1:

**Comment by mvysny** [comment]
Implemented `LocalDate.toFilter()` in 342e73fa1f048d83944f76a955263d53519799ba
