### ISSUE TITLE
`PredicateFilterFactory` not compatible with `buildFilter{}`

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-on-kotlin#46]
`PredicateFilterFactory` is not compatible with `buildFilter{}`.

The `PredicateFilterFactory` was meant to be a way to stay compatible with Vaadin's in-memory data providers (which accept `Predicate<T>` as the filters).

However, the Vaadin In-memory data provider model is utterly broken: in order for it to work properly, it requires support from classes using the API:
1. You need to specify `Grid.Column.comparator` in certain cases instead of just calling `Grid.Column.setSortable(true)`
2. Grid then needs to pass in `Query.inMemorySorting`.
3. There's specialized `InMemoryDataProvider` interface just for in-memory stuff, even though `BackEndDataProvider` can also be used for fetching data from in-memory list.
4. `DataProvider.isInMemory()`: it's highly unclear what that value is used for.

**Comment by mvysny** [comment]
I'm leaning towards removing `PredicateFilterFactory` and suggesting VoK users to use the `DataLoader` API with `Filter` API always (adding a `PredicateFilter` to cater for simple in-memory filtering). That would make `buildFilter{}` to work properly in all scenarios.

However, this would also make certain Grid API unusable with VoK:
1. Grid.setItems() (replaced by a Filter-based Grid.setDataLoaderItems() call in VoK)
2. Grid.Column.comparator (which is a good thing)
3. DataProviders will no longer be used directly (which is probably a good thing as well)
4. Query.inMemorySorting (which is also a good thing since it's confusing)

I believe if we document this properly, then we can actually decrease the level of confusion (e.g. a simple clear instruction of "don't ever set Grid.Column.comparator" versus the current "you might be able to touch that in certain mysterious cases".

**Comment by mvysny** [comment]
@jhult from your experience, have you ever used PredicateFilterFactory and/or Vaadin DataProviders directly? If yes, could you list your use-cases and how hard would it be for you to move to the DataLoader API?

**Comment by jhult** [comment]
@mvysny, I have not used `PredicateFilterFactory` nor the Vaadin `DataProvider` classes. I always use the `DataLoader` API.

**Comment by mvysny** [comment]
Thank you, then I propose to "kill it with fire" :) First it would be good to have a replacement though: https://github.com/mvysny/vok-dataloader/issues/4
