### ISSUE TITLE
Are snapshots publicly available?

### ISSUE THREAD

**Issue by jhult** [mvysny/vaadin-on-kotlin#48]
Are snapshots publicly available?

I've used [JitPack](https://jitpack.io/#mvysny/vaadin-on-kotlin) but bumped into issues in the past (see [here](https://jitpack.io/com/github/mvysny/vaadin-on-kotlin/0.8.2/build.log) for an example).

**Comment by mvysny** [comment]
That error is caused by node.js & npm missing in the build environment. Such kind of error should be fixed in the upcoming VoK release since VoK moved to Vaadin 14.2 and Vaadin Gradle plugin 0.7.0 which is able to automatically download both node.js and npm.

> Are snapshots publicly available?

I'm not sure what you mean, could you please provide more info?

VoK is released to both jcenter and maven repo as well:
1. https://repo1.maven.org/maven2/eu/vaadinonkotlin/
2. https://jcenter.bintray.com/eu/vaadinonkotlin/

**Comment by jhult** [comment]
I'd like to try the latest updates (in this GitHub repository) before you actually release a new version. Often, not yet released versions, are released as "snapshots". See [this StackOverflow article](https://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it) for more information about snapshots.

**Comment by mvysny** [comment]
Gotcha, that makes sense. I understand the concept of snapshots, but I'm not sure what I should do in order to make them public. Could you describe steps to take please?

**Comment by jhult** [comment]
This isn't a high priority for me but it would be nice.

JitPack automatically allows building everything and the repository owned doesn't need to do anything.

If you want to publish snapshots yourself, [this](https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org) looks like the guide to do so.

**Comment by mvysny** [comment]
Thanks! If I understand correctly, if you head to https://jitpack.io/#mvysny/vaadin-on-kotlin and switch to the "Builds" tab, I can see the build for the latest git commit there: currently it's `master-191e0ee6df-1`, and the build log is green, so I think the builds are now succeeding and you can access SNAPSHOTs (or builds for exact commit) at JitPack.

**Comment by jhult** [comment]
This can be closed. As an FYI for others, when using JitPack, I have bumped into some dependency issues between the various sub-modules (artifact) of this project. While not ideal, referencing each artifact individually solves this issue.

When referencing a specific commit as the version, I use this `repository` element:
```
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
    <releases>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
    </releases>
</repository>
```
