### ISSUE TITLE
Adding addons?

### ISSUE THREAD

**Issue by pawaka2020** [mvysny/vaadin-on-kotlin#55]
Hey there, I was wondering if it is possible to add addons?

I've been trying to add this, but I'm not sure how to go about actually doing this.
https://vaadin.com/directory/component/superfields

**Comment by mvysny** [comment]
Hi, it should be just a matter of adding appropriate line into the `build.gradle(.kts)` file, for example:

```
dependencies {
  implementation("org.vaadin.miki:superfields:0.7.3")
}
```

**Comment by pawaka2020** [comment]
Oh it works now, thanks.

**Comment by mvysny** [comment]
No problem :)
