### ISSUE TITLE
vok-framework-v10-vokdb 0.8.3: mvn dependency conflict jdbi-orm

### ISSUE THREAD

**Issue by stapel** [mvysny/vaadin-on-kotlin#58]
vok-db uses jdbi-orm 0.5 while vok-orm uses jdbi-orm 0.7 with vok-framework-v10-vokdb-0.8.3 and maven seems to prefer the former.

This leads to a runtime-error, that the field `databaseVariant` cannot be found in JdbiOrm.

**Comment by mvysny** [comment]
Ouch, my bad, I'm sorry. Thank you so much for pointing it out :+1: I've removed the direct dependency to jdbi-orm so that vok-orm pulls in the right jdbi-orm version automatically.

The workaround for Maven indeed is to manually force jdbi-orm version to 0.7.

Will be fixed in VoK 0.9.0.
