### ISSUE TITLE
Replace Gson with Moshi

### ISSUE THREAD

**Issue by jhult** [mvysny/vaadin-on-kotlin#60]
[Gson](https://github.com/google/gson) is aging. [Moshi](https://github.com/square/moshi) is newer, built on [Okio](https://github.com/square/okio/), and works better with Kotlin.

Moshi also seems to be more performant. Here are some benchmarks:

- https://zacsweers.github.io/json-serialization-benchmarking/
- https://www.ericdecanini.com/2020/10/13/benchmarking-gson-vs-jackson-vs-moshi-2020/

**Comment by mvysny** [comment]
Sounds good! The Okio looks good to me, and Moshi looks configurable enough. Alternative would however be to use kotlinx serialization to JSON... however what I don't like a bit is that it requires a kotlin compiler plugin.

**Comment by mvysny** [comment]
Hmmm, Moshi either requires `kotlin-stdlib` or use kapt: https://github.com/square/moshi#kotlin

Otherwise it will fail with

```
java.lang.IllegalArgumentException: Cannot serialize Kotlin type eu.vaadinonkotlin.restclient.Person. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
```

**Comment by jhult** [comment]
Yeah, it is a bummer that Moshi currently requires `kotlin-reflect` or [kapt](https://kotlinlang.org/docs/reference/kapt.html).

Perhaps the [upcoming migration of Moshi to Kotlin](https://github.com/square/moshi/commit/6e5bb3a29bdfba6f08e96657168167fa2579050b) will make those not required.

**Comment by jhult** [comment]
Not that it is needed but came across this and figured I would link it (in case it proves helpful): https://github.com/slackhq/moshi-gson-interop

**Comment by mvysny** [comment]
Thank you for letting me know, but I think it's better to go with the official kotlinx.serialization package instead. Closing this as won't fix.
