### ISSUE TITLE
Drop Vaadin 14 compatibility

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-on-kotlin#72]
Vaadin 23 LTS is around the corner. Since VoK is only used in new projects which don't require backward compatibility, we can perform backward-incompatible steps such as dropping Vaadin 14 LTS support.

We should drop Vaadin 14 compatibility and focus on Vaadin 23+ only, to simplify the maintenance of this project.

**Comment by mvysny** [comment]
Blocked by https://github.com/vaadin/skeleton-starter-flow/issues/519

**Comment by DALDEI** [comment]
Please keep the old versions around, Im using vok-* in production on vaadin8

**Comment by mvysny** [comment]
> Please keep the old versions around, Im using vok-* in production on vaadin8

@DALDEI sure, let's follow up on that at #74

**Comment by mvysny** [comment]
https://github.com/vaadin/skeleton-starter-flow/issues/519 seems to be resolved :+1: However, we must wait for the new Gradle plugin to be present for Vaadin 23: https://plugins.gradle.org/plugin/com.vaadin
