### ISSUE TITLE
updated vadin8 build with kotlin 1.5

### ISSUE THREAD

**Issue by DALDEI** [mvysny/vaadin-on-kotlin#74]
Is it possible to resurrect the vaadin8 builds, but compiled with kotlin 1.5 ?
Im (still) using vaadin8 and dont expect to be able to upgrade for quite a while - now stuck on version 0.9.1 which is pulling kotlin 1.4

**Comment by mvysny** [comment]
Definitely 👍 let me work on this Tuesday next week; I'll make a release and I'll let you know. Question: perhaps we should go straight to kotliny 1.6?

**Comment by mvysny** [comment]
Hmm Vaadin 8 is approaching end of life in Feb 2022; would be good to upgrade to vaadin 14/23

**Comment by mvysny** [comment]
Hi, I've released vok 0.9.2 with kotlin 1.5.32. Should be shortly in Maven Central: https://repo1.maven.org/maven2/eu/vaadinonkotlin/vok-framework/ Please try it out and let me know :+1:
