### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by jay-peper** [mvysny/vaadin-on-kotlin#95]
Hi,

I've noticed the recent change of upstream dependencies and we'd like to use it as soon as possible. When is the next release planned? Is there anything to help with for the next release?

**Comment by mvysny** [comment]
Hi, thanks for asking, it's actually out already :) Please check out 0.15.0 and/or https://github.com/mvysny/beverage-buddy-vok - you'll have to migrate your imports from javax to jakarta and Java 17+ is now required.

**Comment by jay-peper** [comment]
excellent, thank you
